### ISSUE TITLE
Missing regmap documentation at the documentation page

### ISSUE THREAD

**Issue by bencej98** [MarketSquare/robotframework-construct#16]
Description:
The "robotframework-construct" link in the README points to a documentation page where the `regmap` and `reflector` sections are identical. As a result, the `regmap` documentation is missing.

Steps to Reproduce:
1. Go to the README file of this repository.
2. Click on the "robotframework-construct" link under "What is robotframework-construct?" section.
3. Observe that the `regmap` and `reflector` sections in the documentation are identical.

Expected Behavior:
The `regmap` section should contain the correct documentation for `regmap` keywords.

URL: 
https://marketsquare.github.io/robotframework-construct/

Regmap:
![Screenshot 2024-11-20 162006](https://github.com/user-attachments/assets/ccbc9658-eed2-4853-bc09-749115f4a01b)

Reflector:
![Screenshot 2024-11-20 162125](https://github.com/user-attachments/assets/3831b4d5-3dbd-4b94-b0b3-0bc8d30a29ec)

Thank you!

**Comment by franzhaas** [comment]
Hi [bencej98](https://github.com/bencej98)

Thanks for noting this, this is now fixed with PR.:
https://github.com/MarketSquare/robotframework-construct/pull/17

Best regards,
Franz
