### ISSUE TITLE
Typos in "element" related keywords

### ISSUE THREAD

**Issue by bencej98** [MarketSquare/robotframework-construct#21]
Hi!

I found some typos in some of the element related keywords, see below.

"Elemement" is used instead of "element".

/src/robotframework_construct/__init__.py:

```
@keyword('Elemement `${locator}´ in `${constructDict}´ should be equal to `${expectedValue}´')
@keyword('Elemement `${locator}´ in `${constructDict}´ should not be equal to `${expectedValue}´')
@keyword('Get elemement `${locator}´ from `${constructDict}´')
@keyword('Modify the elemement located at `${locator}´ of `${constructDict}´ to `${value}´')

```

Kind regards,
Bence

**Comment by franzhaas** [comment]
Thanks!

Would you mind to fork and create a pull request? 

That way you would get attribution for your work and i believe its just better for everyone involved...

Best regards,
Franz

**Comment by franzhaas** [comment]
After looking at it in the user guide https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#keyword-decorator I think the way it is matches the way it is described there

First letter of the embedded keyword captialised, no point at the end.

What do you think?

**Comment by bencej98** [comment]
Yes it does match the Robot user guide, however I was referring to the misspelling of the word "element" here, because right now in each keyword the word "elemement" is present. I hope I understood your comment the right way. I can create a pull request with renaming the keyword decorators to "element" if you want and in this the documentation should be updated as well to match it.

**Comment by franzhaas** [comment]
Ah sorry, I overlooked that. 

Yes please go ahead and make a pull request, the documentation is generated from the *.py files and I will regenerate it. Fixing the code is enough.

Thanks for pointing me to the issue, looking forward to a Pull request
Franz

**Comment by franzhaas** [comment]
did it together with `´ -> ' change as requested by tatu
